"""Configuration for Rosh Creatives Lead Agent."""

BRAND = {
    "company": "Rosh Creatives",
    "founder": "Roshith R Menon",
    "phone": "+91 94473 36560",
    "email": "rosh.musik@gmail.com",
    "website": "https://www.roshmusik.com",
    "tagline": "Ads that sing.",
    "past_work": [
        "Kukuntha Bridal Lounge",
        "Kaalan Aaryavaidhyasaala",
    ],
    "services": [
        "Video advertisements",
        "Radio jingles & audio ads",
        "Social media reels",
        "Brand sound design",
    ],
    "booking_link": "",
}

# Autonomous agent settings (Level B: auto-send routine replies, draft complex ones).
AGENT = {
    "max_pitches_per_day": 40,
    "max_auto_replies_per_day": 80,
    "seconds_between_sends": 12,
    "auto_send_intents": [
        "interested",
        "wants_info",
        "wants_price",
        "not_interested",
        "unsubscribe",
        "out_of_office",
    ],
    "always_draft_intents": [
        "complex",
        "complaint",
        "angry",
        "legal",
    ],
}

CATEGORIES = [
    # Wedding & fashion
    "bridal lounge",
    "jewellery shop",
    "textile showroom",
    "saree showroom",
    "boutique",
    "wedding photographer",
    "wedding planner",
    "event planner",
    "catering service",
    "wedding hall",
    # Beauty & wellness
    "beauty salon",
    "spa",
    "ayurveda clinic",
    "ayurvedic pharmacy",
    "dental clinic",
    "skin clinic",
    "eye hospital",
    "hospital",
    "fitness gym",
    "yoga studio",
    # Food
    "restaurant",
    "cafe",
    "bakery",
    "sweet shop",
    "ice cream parlour",
    "cloud kitchen",
    # Education
    "school",
    "coaching centre",
    "tuition centre",
    "music school",
    "dance school",
    "driving school",
    "computer training institute",
    # Real estate & home
    "real estate agency",
    "builders",
    "interior designer",
    "furniture showroom",
    "home appliances showroom",
    "modular kitchen showroom",
    # Auto
    "car showroom",
    "used car dealer",
    "bike showroom",
    "car service centre",
    # Travel & hospitality
    "hotel",
    "resort",
    "homestay",
    "travel agency",
    "tour operator",
    # Retail
    "electronics shop",
    "mobile shop",
    "supermarket",
    "optical shop",
    "footwear store",
    "kids store",
    "pet shop",
    # Services
    "photography studio",
    "printing press",
    "advertising signboard",
    "courier service",
    "packers and movers",
    "veterinary clinic",
]

KERALA_CITIES = [
    "Thiruvananthapuram",
    "Kollam",
    "Pathanamthitta",
    "Alappuzha",
    "Kottayam",
    "Idukki",
    "Ernakulam",
    "Thrissur",
    "Palakkad",
    "Malappuram",
    "Kozhikode",
    "Wayanad",
    "Kannur",
    "Kasaragod",
]

TAMILNADU_CITIES = [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Vellore",
    "Erode",
    "Thoothukudi",
    "Dindigul",
    "Thanjavur",
    "Ranipet",
    "Sivaganga",
    "Karur",
    "Namakkal",
    "Kanchipuram",
    "Tiruvannamalai",
    "Pudukkottai",
    "Nagapattinam",
    "Cuddalore",
    "Villupuram",
    "Krishnagiri",
    "Dharmapuri",
    "Theni",
    "Virudhunagar",
    "Ramanathapuram",
    "Kanyakumari",
    "Nilgiris",
    "Ariyalur",
    "Perambalur",
    "Tenkasi",
    "Chengalpattu",
    "Tirupathur",
    "Mayiladuthurai",
    "Kallakurichi",
    "Tiruvallur",
    "Tiruvarur",
]

# Backwards-compatible: full coverage for the daily rotation
ALL_CITIES = KERALA_CITIES + TAMILNADU_CITIES
