"""Configuration for Rosh Creatives Lead Agent."""

BRAND = {
    "company": "Rosh Creatives",
    "founder": "Roshith R Menon",
    "phone": "+91 94473 36560",
    "email": "rosh.musik@gmail.com",
    "website": "https://www.roshmusik.com",
    "tagline": "Ads that sing.",
    "past_work": [
        "Kukuntha Bridal Lounge",
        "Kaalan Aaryavaidhyasaala",
    ],
    "services": [
        "Video advertisements",
        "Radio jingles & audio ads",
        "Social media reels",
        "Brand sound design",
    ],
}

CATEGORIES = [
    "bridal lounge",
    "jewellery shop",
    "textile showroom",
    "saree showroom",
    "ayurveda clinic",
    "ayurvedic pharmacy",
    "beauty salon",
    "spa",
    "wedding photographer",
    "event planner",
    "restaurant",
    "catering service",
]

KERALA_CITIES = [
    "Thiruvananthapuram",
    "Kollam",
    "Pathanamthitta",
    "Alappuzha",
    "Kottayam",
    "Idukki",
    "Ernakulam",
    "Thrissur",
    "Palakkad",
    "Malappuram",
    "Kozhikode",
    "Wayanad",
    "Kannur",
    "Kasaragod",
]

TAMILNADU_CITIES = [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Vellore",
    "Erode",
    "Thoothukudi",
    "Dindigul",
    "Thanjavur",
    "Ranipet",
    "Sivaganga",
    "Karur",
    "Namakkal",
    "Kanchipuram",
    "Tiruvannamalai",
    "Pudukkottai",
    "Nagapattinam",
    "Cuddalore",
    "Villupuram",
    "Krishnagiri",
    "Dharmapuri",
    "Theni",
    "Virudhunagar",
    "Ramanathapuram",
    "Kanyakumari",
    "Nilgiris",
    "Ariyalur",
    "Perambalur",
    "Tenkasi",
    "Chengalpattu",
    "Tirupathur",
    "Mayiladuthurai",
    "Kallakurichi",
    "Tiruvallur",
    "Tiruvarur",
]

# Backwards-compatible: full coverage for the daily rotation
ALL_CITIES = KERALA_CITIES + TAMILNADU_CITIES
